version: '3.8'

services:
  piko:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - TZ=UTC
    volumes:
      - ./config:/app/config
      - blockchain_data:/app/data
    restart: unless-stopped
    networks:
      - piko-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: piko
      MYSQL_USER: piko
      MYSQL_PASSWORD: pikopassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - piko-network

volumes:
  mysql_data:
  blockchain_data:

networks:
  piko-network:
    driver: bridge 